language: ruby

env:
  global:
    - DISCOURSE_HOSTNAME=www.example.com

dist: trusty

cache: bundler

addons:
  postgresql: 9.5
  apt:
    packages:
    - gifsicle
    - jpegoptim
    - optipng
    - jhead

rvm:
  - 2.3.1

services:
  - redis-server

before_install:
  - git clone https://github.com/discourse/discourse.git discourse
  - cd discourse

install:
  - touch config/stripe.yml
  - ln -s ../discourse-donations plugins/discourse-donations
  - ls -l plugins
  - ls -l plugins/discourse-donations

before_script:
  - gem install bundler
  - bundle install
  - bundle exec rake db:create db:migrate

script:
  - "bundle exec rake plugin:spec[discourse-donations] && bundle exec rake qunit:test['200000']"
