language: ruby

env:
  global:
    - DISCOURSE_HOSTNAME=www.example.com

dist: trusty

addons:
  postgresql: 9.5
  apt:
    packages:
    - gifsicle
    - jpegoptim
    - optipng
    - jhead

rvm:
  - 2.3.1

services:
  - redis-server

before_install:
  - git clone https://github.com/discourse/discourse.git discourse
  - cd discourse

install:
  - touch config/stripe.yml
  - git clone https://github.com/choiceaustralia/discourse-payments.git plugins/discourse-payments --depth=1

before_script:
  - gem install bundler
  - bundle install
  - bundle exec rake db:create db:migrate

script:
  - "bundle exec rake plugin:spec && bundle exec rake qunit:test['200000']"
