plugins:
  discourse_patrons_enabled:
    default: false
  discourse_patrons_public_key:
    default: ''
    client: true
  discourse_patrons_secret_key:
    default: ''
    client: false
  discourse_patrons_description:
    client: true
    default: ''
  discourse_patrons_currency:
    client: true
    default: "USD"
    type: enum
    choices:
      - AUD
      - CAD
      - EUR
      - JPY
      - GBP
      - USD
