plugins:
  discourse_donations_enabled:
    default: true
    client: true
  discourse_donations_secret_key:
    type: text
    client: true
  discourse_donations_public_key:
    type: text
    client: true
